[pytest]
filterwarnings =
    ignore:.*iscoroutinefunction.*deprecated:DeprecationWarning:fastapi
    ignore:.*iscoroutinefunction.*deprecated:DeprecationWarning:starlette
    ignore:The 'app' shortcut is now deprecated:DeprecationWarning:httpx
    ignore:datetime\.datetime\.utcnow\(\) is deprecated:DeprecationWarning:jose
