"""initial_schema

Revision ID: f46e9b10ec7a
Revises: 
Create Date: 2026-08-16 20:41:33.152980

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f46e9b10ec7a'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('appointments', sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False))
    op.add_column('appointments', sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False))
    op.alter_column('appointments', 'patient_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('appointments', 'doctor_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('appointments', 'appointment_date',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('appointments', 'status',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.drop_constraint(op.f('appointments_patient_id_fkey'), 'appointments', type_='foreignkey')
    op.create_foreign_key(None, 'appointments', 'patients', ['patient_id'], ['id'], ondelete='RESTRICT')
    op.create_foreign_key(None, 'appointments', 'doctors', ['doctor_id'], ['id'], ondelete='CASCADE')
    op.add_column('bills', sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False))
    op.add_column('bills', sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False))
    op.alter_column('bills', 'patient_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('bills', 'doctor_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('bills', 'amount',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('bills', 'payment_status',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.drop_constraint(op.f('bills_patient_id_fkey'), 'bills', type_='foreignkey')
    op.create_foreign_key(None, 'bills', 'patients', ['patient_id'], ['id'], ondelete='RESTRICT')
    op.create_foreign_key(None, 'bills', 'doctors', ['doctor_id'], ['id'], ondelete='CASCADE')
    op.add_column('doctors', sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False))
    op.add_column('doctors', sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False))
    op.alter_column('doctors', 'clinic_name',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.add_column('patients', sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False))
    op.add_column('patients', sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False))
    op.alter_column('patients', 'doctor_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('patients', 'address',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=True)
    op.alter_column('patients', 'blood_group',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=True)
    op.alter_column('patients', 'medical_history',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=True)
    op.create_foreign_key(None, 'patients', 'doctors', ['doctor_id'], ['id'], ondelete='CASCADE')
    op.add_column('treatments', sa.Column('treatment_date', sa.DateTime(timezone=True), nullable=True))
    op.add_column('treatments', sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False))
    op.add_column('treatments', sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False))
    op.alter_column('treatments', 'patient_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('treatments', 'doctor_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('treatments', 'status',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.drop_constraint(op.f('treatments_patient_id_fkey'), 'treatments', type_='foreignkey')
    op.create_foreign_key(None, 'treatments', 'patients', ['patient_id'], ['id'], ondelete='RESTRICT')
    op.create_foreign_key(None, 'treatments', 'doctors', ['doctor_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'treatments', type_='foreignkey')
    op.drop_constraint(None, 'treatments', type_='foreignkey')
    op.create_foreign_key(op.f('treatments_patient_id_fkey'), 'treatments', 'patients', ['patient_id'], ['id'])
    op.alter_column('treatments', 'status',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('treatments', 'doctor_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('treatments', 'patient_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.drop_column('treatments', 'updated_at')
    op.drop_column('treatments', 'created_at')
    op.drop_column('treatments', 'treatment_date')
    op.drop_constraint(None, 'patients', type_='foreignkey')
    op.alter_column('patients', 'medical_history',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('patients', 'blood_group',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('patients', 'address',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('patients', 'doctor_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.drop_column('patients', 'updated_at')
    op.drop_column('patients', 'created_at')
    op.alter_column('doctors', 'clinic_name',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.drop_column('doctors', 'updated_at')
    op.drop_column('doctors', 'created_at')
    op.drop_constraint(None, 'bills', type_='foreignkey')
    op.drop_constraint(None, 'bills', type_='foreignkey')
    op.create_foreign_key(op.f('bills_patient_id_fkey'), 'bills', 'patients', ['patient_id'], ['id'])
    op.alter_column('bills', 'payment_status',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('bills', 'amount',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('bills', 'doctor_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('bills', 'patient_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.drop_column('bills', 'updated_at')
    op.drop_column('bills', 'created_at')
    op.drop_constraint(None, 'appointments', type_='foreignkey')
    op.drop_constraint(None, 'appointments', type_='foreignkey')
    op.create_foreign_key(op.f('appointments_patient_id_fkey'), 'appointments', 'patients', ['patient_id'], ['id'])
    op.alter_column('appointments', 'status',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('appointments', 'appointment_date',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('appointments', 'doctor_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('appointments', 'patient_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.drop_column('appointments', 'updated_at')
    op.drop_column('appointments', 'created_at')
    # ### end Alembic commands ###
